version : '3'
services:
  mongodb
   image: mvertes/alpine-mongo
   networks:
    - bask-tier
   volumes:
    - db-data:/data/db
   backend:
   build: .
   command: nodemon . --exitcrash
   volumes:
    - .:/app
    - dependencies:/app/node_modules
   ports:
    - "3003:3000"
   links:
    - db-mongo
   environment:
    - PORT=3000
    - NODE_END=development
   networks:
     front-tier:
       driver: bridge
     back-tier:
       driver: bridge
volumes:
  dependencies:
  db-data:
