version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://localhost:80/mongo
  mongodb:
    image: mvertes/alpine-mongo
    networks:
     - back-tier
    command: nodemon . --exitcrash
    volumes:
     - db-data:/data/db
    ports:
     - "3001:3001"
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
volumes:
  dependencies:
  db-data:

