  version: '3'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}
  mongo:
    image: mvertes/alpine-mongo
    environment:
      MONGO_HOST=localhost
      MONGO_PORT=80
      MONGO_DATABASE=mongo
